# Generated by Django 2.2 on 2020-03-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='adverts.Advert'),
        ),
    ]
