# Generated by Django 2.2 on 2020-03-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advert_user'),
        ('users', '0004_auto_20200317_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='adverts.Advert'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
