# Generated by Django 2.2 on 2020-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200317_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='users', to='adverts.Advert'),
        ),
    ]
