# Generated by Django 2.2 on 2020-04-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='file',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='ads_pics'),
        ),
    ]
