# Generated by Django 2.2 on 2020-02-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='slug',
            field=models.SlugField(default='null', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
