# Generated by Django 2.2 on 2020-02-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_advert_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='ad_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
