# Generated by Django 2.2 on 2020-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advert_ad_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='ad_pic',
            field=models.ImageField(null=True, upload_to='ads_pics'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
