# Generated by Django 2.2 on 2020-03-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_imagfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagfile',
            name='name',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
