# Generated by Django 2.2 on 2020-03-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_imagfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagfile',
            name='name',
        ),
    ]
