# Generated by Django 2.2 on 2020-03-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0008_remove_imagfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='ad_pic',
            field=models.ImageField(default='null', upload_to='ads_pics'),
            preserve_default=False,
        ),
    ]
