# Generated by Django 2.2 on 2020-03-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0010_auto_20200302_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='image',
            new_name='file',
        ),
    ]
